
name: Remote Backup Trigger

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Backup Script
        run: |
          chmod +x ./backup.sh
          ./backup.sh
